### ISSUE TITLE
Submodule geas source code not available 

### ISSUE THREAD

**Issue by mansalskog** [ed-lam/nutmeg#1]
The submodule geas does not seem to be available anymore, as https://bitbucket.org/gkgange/geas.git is not a public repository.

**Comment by ed-lam** [comment]
You are right. I will find out where is the Geas source code these days. In the meantime, I have uploaded my old copy of it. You can try to clone it with submodules again.

**Comment by mansalskog** [comment]
Awesome! Thank you very much!
